require("config.options")
require("plugins.github-theme")
require("plugins.telescope")
require("plugins.nvim-treesitter")
require("plugins.nvim-ts-autotag")
require("plugins.comment")
require("plugins.nvim-cmp")

require("config.lsp")
require("config.autocmds")
require("config.keymaps")
